/**
 * Activation Generator Types
 * 
 * Types for generating marketing activation drafts from completed high-impact tasks.
 */

import type { ThemeCategory, ActivationDraftType, ActivationDraftStatus } from '@prisma/client';

// Input for generating activation drafts
export interface ActivationGeneratorInput {
  taskId: string;
  tenantId: string;
  themeId: string;
  themeCategory: ThemeCategory;
  themeName: string;
  deltaS: number;
  fixScore: number;
  taskTitle: string;
  taskDescription?: string | null;
  impactNotes?: string | null;
  tenantName: string;
}

// Generated draft content
export interface GeneratedDraft {
  draftType: ActivationDraftType;
  title: string;
  content: string;
  metadata?: Record<string, unknown>;
}

// Template variables for content generation
export interface TemplateVariables {
  tenantName: string;
  themeName: string;
  themeCategory: ThemeCategory;
  improvement: string; // e.g., "improved", "enhanced", "upgraded"
  improvementVerb: string; // e.g., "improve", "enhance", "upgrade"
  aspect: string; // e.g., "food quality", "customer service", "cleanliness"
  positiveAdjective: string; // e.g., "delicious", "friendly", "spotless"
  callToAction: string;
  hashtags: string[];
  offerType?: string;
  offerDetails?: string;
}

// Theme-specific configuration for templates
export interface ThemeTemplateConfig {
  aspect: string;
  positiveAdjectives: string[];
  improvements: string[];
  callToActions: string[];
  hashtags: string[];
  offerSuggestions: OfferSuggestion[];
}

export interface OfferSuggestion {
  title: string;
  description: string;
  type: 'discount' | 'bundle' | 'loyalty' | 'special';
  relevanceThreshold: number; // Minimum deltaS to suggest this offer
}

// Result of activation generation
export interface ActivationGenerationResult {
  success: boolean;
  drafts: GeneratedDraft[];
  error?: string;
  /** Indicates whether content was generated by AI or templates */
  generatedBy?: 'ai' | 'template';
}

// Thresholds for triggering activation generation
export const ACTIVATION_THRESHOLDS = {
  MIN_DELTA_S: 0.1, // Minimum positive sentiment change to trigger
  HIGH_IMPACT_DELTA_S: 0.3, // Threshold for high-impact offers
  MIN_FIX_SCORE: 0.05, // Minimum FixScore to qualify
} as const;
